Optimize follow logs implementation
pesos/heiko pull request #9
Opened 2021-01-29 15:58 UTC by MadhavJivrajani

The CPU usage is nearly 0% for the `follow` logs implementation
Implemented using the `subprocess` module.

![Screenshot from 2021-01-29 21-24-01](https://user-images.githubusercontent.com/12381034/106297432-b4920c80-6278-11eb-9a5b-9c3e0d5460ab.png)
![Screenshot from 2021-01-29 21-24-49](https://user-images.githubusercontent.com/12381034/106297441-b8259380-6278-11eb-9b5e-0b8ff757b523.png)

- [x] ran the code through `black`
Fixes #7

2021-02-02 03:31 UTC, Samyak2 requested changes
CPU Usage is at a constant 0.0. This is nice!

There is one issue though. Since you're using `-F` (as opposed to `-f`), when the user provides a name that does not exist, `tail` keeps trying to open the file and the command gets stuck there without any error.

2021-02-02 03:31 UTC, Samyak2 commented on heiko/cli.py
>      while True:
```suggestion
    f = subprocess.Popen(
        ["tail", "-f", file_path], stdout=subprocess.PIPE, stderr=subprocess.PIPE
    )
    for line in f.stdout:
```

2021-02-02 03:31 UTC, Samyak2 commented on heiko/cli.py
> +        yield f.stdout.readline().decode()
```suggestion
        yield line
```

2021-02-02 03:31 UTC, Samyak2 commented on heiko/cli.py
>      while True:
This (along with the next suggestion - GitHub wouldn't let me suggest changes to the whole thing at once) should fix the issue I described.

2021-02-02 05:08 UTC, MadhavJivrajani commented on heiko/cli.py
>      while True:
I had tried this locally, it doesn't print logs as and when appended. Only if you stop the command will it print the logs, I'm not sure why that happens yet.

2021-02-02 05:09 UTC, MadhavJivrajani commented on heiko/cli.py
> +        yield f.stdout.readline().decode()
I think `decode()` might be needed because the items that `f.stdout` produces will be a byte strings.

2021-02-02 05:13 UTC, MadhavJivrajani commented on heiko/cli.py
>      while True:
We can do 
```py
f = subprocess.Popen(
        ["tail", "-f", file_path], stdout=subprocess.PIPE, stderr=subprocess.PIPE, universal_newlines=True
)
for line in iter(f.stdout.readline, ""):
        yield line

2021-02-02 05:17 UTC, MadhavJivrajani commented on heiko/cli.py
> +        yield f.stdout.readline().decode()
If the above approach that I mentioned is used, then `decode()` isn't needed

2021-02-02 05:40 UTC, Samyak2 commented on heiko/cli.py
>      while True:
> I had tried this locally, it doesn't print logs as and when appended. Only if you stop the command will it print the logs, I'm not sure why that happens yet.

Oof. I only checked if it worked when an invalid file was given.




> We can do this, this works:
> 
> ```python
> f = subprocess.Popen(
>         ["tail", "-f", file_path], stdout=subprocess.PIPE, stderr=subprocess.PIPE, universal_newlines=True
> )
> for line in f.stdout:
>         yield line
> ```

That works! But maybe use `text=True` instead of `universal_newlines=True`. From the [docs](https://docs.python.org/3/library/subprocess.html#popen-constructor):
> The universal_newlines argument is equivalent to text and is provided for backwards compatibility.

---

> Also, what was the issue with
> 
> ```python
> while True:
>      yield f.stdout.readline().decode()
> ```

The issue was that, when the file didn't exist and `stdout` was empty, it would be stuck in an infinite loop there (also it probably would have entered an infinite loop after the file ends, not sure though).

(in hindsight, I should have explained the changes earlier xD)

2021-02-02 05:40 UTC, Samyak2 commented on heiko/cli.py
> +        yield f.stdout.readline().decode()
Right

2021-02-02 05:51 UTC, MadhavJivrajani commented on heiko/cli.py
>      while True:
Hey, I found another way that might be neater:
```py
subprocess.run(["tail", "-f", file_path], stdout=sys.stdout, stderr=sys.stderr, check=True)
```
> The issue was that, when the file didn't exist and stdout was empty, it would be stuck in an infinite loop there (also it probably would have entered an infinite loop after the file ends, not sure though).

Oh right, makes sense

2021-02-02 06:02 UTC, Samyak2 commented on heiko/cli.py
>      while True:
> Hey, I found another way that might be neater, the CPU usage is the same as the current commit, constant 0%
> 
> ```python
> subprocess.run(["tail", "-f", file_path], stdout=sys.stdout, stderr=sys.stderr, check=True)
> ```

Oh that's great, it works well. One issue though - when the file doesn't exist, the error is a bit verbose and doesn't indicate the issue to the user directly (the issue being that the `name` is wrong). A try-except around it with an error message printed on `subprocess.CalledProcessError` would be nice.

2021-02-02 06:19 UTC, MadhavJivrajani commented on heiko/cli.py
>      while True:
Hmm.
I have one question though. The file not existing error will be raised if the `--name` flag has an invalid value set. Shouldn't that be handled before the execution of following logs in executed? That's done while handling the `init` command in `cli.py`. The reason why handling this explicitly beforehand might be better is because the error message can clearly say that the `--name` value does not exist or something equivalent?

2021-02-02 06:35 UTC, Samyak2 commented on heiko/cli.py
>      while True:
That's a great point. The `name` should be checked before any of the commands are executed. IIRC the only way to check if the name is correct is to see if the log file exists (`heiko_<name>.out`). Since `start`, `stop` and `restart` check for the name using the PID file and `init` does not need the name to exist, the only other sub-command that needs `name` to exist is `logs`.

We should add a check for the log file right at the start of the `elif args.command == "logs":` block and print an error if it doesn't exist. Let me know I missed something (or if I missed the point xD). If you wish, you can open a separate issue for this and I can merge this PR with the `subprocess.run` change you found earlier.

2021-02-02 08:05 UTC, MadhavJivrajani commented
Hey, 
I've added the check and I switched to `check_call()` instead of `run()` since it raises the `subprocess.CalledProcessError` for any non-zero return codes.

2021-02-02 08:14 UTC, MadhavJivrajani commented
(also, if this looks good, don't merge yet, I wanted to checkout one other thing)

2021-02-02 13:15 UTC, Samyak2 reviewed
LGTM!

Just one thing

2021-02-02 13:15 UTC, Samyak2 commented on heiko/cli.py
>      """
Since this function isn't really limited to checking the log file and it can be used for any path, you could make this a `file_exists` function that works for any path. The current name and doc would make sense if just the name was passed to it, but as it stands rn the function requires the user (of the function) to get the path to the log file beforehand.

2021-02-02 15:43 UTC, MadhavJivrajani commented on heiko/cli.py
>      """
Makes sense, will do

2021-02-02 17:34 UTC, Samyak2 commented on heiko/cli.py
>      """
Can you also change the doc string to reflect the new name?

2021-02-03 11:09 UTC, MadhavJivrajani commented on heiko/cli.py
>      """
Will do

2021-02-03 14:32 UTC, Samyak2 approved these changes
LGTM. Thank you!

2021-02-03 14:38 UTC, merged